services:
  cluster-1:
    build:
      args:
        NETWORK: mainnet
        P2P_TCP_PORT: 3411
        P2P_UDP_PORT: 3431
    ports:
      - 3411:3411/tcp
      - 3431:3431/udp
  cluster-2:
    build:
      args:
        NETWORK: mainnet
        P2P_TCP_PORT: 3412
        P2P_UDP_PORT: 3432
    ports:
      - 3412:3412/tcp
      - 3432:3432/udp
  cluster-3:
    build:
      args:
        NETWORK: mainnet
        P2P_TCP_PORT: 3413
        P2P_UDP_PORT: 3433
    ports:
      - 3413:3413/tcp
      - 3433:3433/udp
  cluster-4:
    build:
      args:
        NETWORK: mainnet
        P2P_TCP_PORT: 3414
        P2P_UDP_PORT: 3434
    ports:
      - 3414:3414/tcp
      - 3434:3434/udp
  cluster-5:
    build:
      args:
        NETWORK: mainnet
        P2P_TCP_PORT: 3415
        P2P_UDP_PORT: 3435
    ports:
      - 3415:3415/tcp
      - 3435:3435/udp
